/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.rivetlogic.training.todo.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rivetlogic.training.todo.model.Todo;
import com.rivetlogic.training.todo.service.TodoLocalServiceUtil;

/**
 * The extended model base implementation for the Todo service. Represents a row in the &quot;training_Todo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TodoImpl}.
 * </p>
 *
 * @author rivetlogic
 * @see TodoImpl
 * @see com.rivetlogic.training.todo.model.Todo
 * @generated
 */
public abstract class TodoBaseImpl extends TodoModelImpl implements Todo {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a todo model instance should use the {@link Todo} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			TodoLocalServiceUtil.addTodo(this);
		}
		else {
			TodoLocalServiceUtil.updateTodo(this);
		}
	}
}